baseURL: "https://purplelightstudios.github.io/"
languageCode: "en-us"
theme: "tailbliss"

title: PurpleLight Studios
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 9
darkmode_js:
  - assets/js/darkmode.js
enableInlineShortcodes: true

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

params:
  title_description: Streaming Tech for a new age
  ShowFullIntroVideoSlide: true
  ShowFullIntroSlide: false
  ShowSimpleIntroSlide: false
  ShowSponsors: false
  IncludeStars: false
  NavbarSizeClass: max-w-full

  secondaryTitles: Legal,Contact
  DisableStayUptodateHome: false
  DisableStayUptodateList: false
  DisableStayUptodateSingle: false

  GeneralHtmlClass: dark # Set to dark and DisableThemeToggle to run theme in dark mode by default
  DisableThemeToggle: true

  author: PurpleLight Studios
  authorimage: ../assets/images/global/author.webp
  og_image: /images/tailbliss-cover.png

  FullIntroVideo:
    title: Streaming Tech
    subtitle: For a new age
    description: "Engage with your enterprise clients or your community followers using the best streaming solutions in the market. Simplify your technology stack without compromising quality."

    VideoUrl: https://videos.pexels.com/video-files/8303104/8303104-hd_1920_1080_24fps.mp4
    VideoType: video/mp4

    link:
      text: More info
      url: /about/

    EnableQuotes: true
    QuoteTitle: "Empowering"
    Quotes: "Content creators,Web developers,Streamers,Innovators,Game developers"

  AboutUsIntro:
    title: About us
    subtitle: Who we are
    description: "We provide the best video, audio and data streaming technologies alongside with consulting to ensure the best quality and efficency to our costumers."
    image: "/streaming.jpg"

  AboutUs:
    heading: "Our mission"
    subheading: "Empower creative people, using technology as a foundation, to take on high risk projects without compromising quality or artistic vision."
    content:
      - title: "Streaming technology"
        text: "We create high quality streaming solutions to deliver media contents at massive scale."
        link:
          text: Contact us
          url: /contact/
        icon: gamepad

  ServicesIntro:
    title: Our services
    subtitle: How do we work?
    description: "We work with clients from Colombia and United States of America that need to implement high quality streaming solutions.
From Cloud Solutions, Custom Codecs and even custom developments, we've got you covered with our tech solutions!"
    image: "/services.jpg"

  streaming:
    heading: "Streaming technology"
    image: "/a.jpg"
    content:
      - text: "We create high quality streaming solutions to deliver media contents at massive scale."
      - text: "Our team develops customized video and audio codecs with one goal in mind: optimization without quality lost."
      - text: "Contact us and start a painless content creator journey!"
    link:
      text: Contact us
      url: /contact
  software:
    heading: "Software development"
    image: "/b.jpg"
    content:
      - text: "We offer remote third party development services, whenever your solution requires web, deskop or mobile coding, we create high quality software using industry best practices and top notch technology."
      - text: "Our software is written using the best tools in the market and appliying the best software design practices including JS, TS, Rust, C/C++, .NET, and many other technologies."
      - text: "Contact us and start your custom development with a highly qualified team of software engineers."
    link:
      text: Contact us
      url: /contact
  consulting:
    heading: "Consulting"
    image: "/c.jpg"
    content:
      - text: "For projects requiring help implementing streaming solutions, new technology or agile practices, our industry experts can help you tunning your dev-team boosting your productivity."
      - text: "- Streaming experts."
      - text: "- Agile leaders and scrum masters."
      - text: "- Software consulting."
    link:
      text: Contact us
      url: /contact

  openSource:
    heading: "Open Source"
    image: "/intro-2.jpg"
    content:
      - text: "Our team is commited to create open solutions that anyone, anywhere can start using for free. As part of our mission to empower programmers and creators we are constantly contributing to the open source community."
      - text: "- Custom OBS versions optimized for the heaviest workloads."
      - text: "- Aseprite UVPadder, PixelSkinGenerator and Exporter to Paper2D (Unreal Engine)"
      - text: "- More projects comming soon!"
    link:
      text: Official GitHub
      url: https://github.com/purplelightstudios

  solutions:
    heading: "What we do"
    subheading: "Simplifying technology workflows"
    content:
      - title: "Streaming technology"
        text: "We create high quality streaming solutions to deliver media contents at massive scale."
        link:
          text: Our services
          url: /services/
        icon: towercell
      - title: "Software development"
        text: "We offer remote third party development services, whenever your solution requires web, deskop or mobile coding, we create high quality software using industry best practices and top notch technology."
        link:
          text: Our services
          url: /services/
        icon: laptop-code
      - title: "Consulting"
        text: "For projects requiring help implementing streaming solutions, new technology or agile practices, our industry experts can help you tunning your dev-team boosting your productivity."
        link:
          text: Our services
          url: /services/
        icon: people-group
      - title: "Open Source"
        text: "Our team is commited to create open solutions that anyone, anywhere can start using for free. As part of our mission to empower programmers and creators we are constantly contributing to the open source community."
        icon: computer
        link:
          text: Our services
          url: /services/

  details:
    heading: "Who we are"
    image: "/intro-1.jpg"
    content:
      - text: "We provide the best video, audio and data streaming technologies alongside with consulting to ensure the best quality and efficency to our costumers."
      - text: "Our team develops customized video and audio codecs with one goal in mind: optimization without quality lost."
    link:
      text: Read more
      url: /about
  moreDetails:
    heading: "Community driven"
    image: "/com.jpg"
    content:
      - text: "We believe in the power of communities so we are fully commited with open source solutions, sharing and contributing to different projects around the world."
      - text: "- Custom OBS versions optimized for the heaviest workloads."
      - text: "- Aseprite UVPadder, PixelSkinGenerator and Exporter to Paper2D (Unreal Engine)"
      - text: "- More projects comming soon!"
    link:
          text: Our services
          url: /services/

  sponsors:
    heading: "Backed by world-renowned investors"
    content:
      - text: "Sagittis scelerisque nulla cursus in enim consectetur quam. Dictum urna sed consectetur neque tristique pellentesque. Blandit amet, sed aenean erat arcu morbi. Cursus faucibus nunc nisl netus morbi vel porttitor vitae ut. Amet vitae fames senectus vitae."
    links:
      - text: Meet our investors and advisors
        url: "#"
    logos:
      - identifier: a
        image: "images/global/sample-logo.svg"
        alt: "a"
      - identifier: b
      - identifier: c
      - identifier: d
      - identifier: e
      - identifier: f
  fromTheBlog:
    heading: "From the blog"
    content:
      - text: "News, releases and devlogs."

  stayUpToDate:
    heading: "Let's talk!"
    content:
      - text: "Contact us and schedule an appoinment to discuss your needs."
    showForm: false
    showSocial: true
    action: "#"
    label: "Email address"
    placeholder: "Enter your email"
    button: "Notify me"
    link:
        text: Contact us
        url: /contact/

  social:
    github:
      enabled: true
      url: 'https://github.com/purplelightstudios'
    facebook:
      enabled: true
      url: 'https://facebook.com/purplelightstudios'
    instagram:
      enabled: false
      url: 'https://instagram.com/purplelightstudios'
    linkedin:
      enabled: true
      url: 'https://www.linkedin.com/company/purplelightstudios'
    twitter:
      enabled: true
      url: '@purplelightstudios'


menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: services
      name: Services
      url: /services
      weight: 11
    - identifier: about
      name: About
      url: /about
      weight: 12
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 20
    - identifier: dropdown
      pre: complexdropdown
      name: Open-Source
      weight: 40
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50
    - identifier: legal
      name: Legal
      url: /legal/
      weight: 60
  categories:
    - identifier: prose
      name: Prose
      url: /prose/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
  dropdown:
    - identifier: github
      pre: piechart # can be stars, comments or piechart
      name: Custom OBS
      post: "GitHub repo"
      url: "https://github.com/purplelightstudios/obs-studio-optimized"
      weight: 10
    - identifier: githubgs
      pre: stars # can be stars, comments or piechart
      name: Other projects
      post: "GitHub profile"
      url: "https://github.com/purplelightstudios"
      weight: 20
  footer:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 20
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 50
    - identifier: legal
      name: Legal
      url: /legal/
      weight: 60

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: Categories
  tag: Tags

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: true
    respectDoNotTrack: true
    useSessionStorage: false
  instagram:
    disable: true
    simple: false
  twitter:
    disable: true
    enableDNT: false
    simple: false
  vimeo:
    disable: false
    enableDNT: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

module:
  hugoVersion:
    extended: true
    min: "0.104.0"
